language: node_js
    - 10
    - 9
    - 8
    - 7
    - 6
before_install:
    - sudo add-apt-repository ppa:duggan/bats --yes
    - sudo apt-get update -qq
    - sudo apt-get install -qq bats
    - sudo apt-get install shellcheck
    - sudo apt-get install nodejs
    - sudo apt-get install npm
    - sudo ln -s /usr/bin/nodejs /usr/bin/node
    - npm install -g markdownlint-cli
script:
    - bats test.bats
