#!/usr/bin/env bash

# cub
#
# wolfram|alpha queries from the terminal
# --------

# get app id

if [ -f ~/.cub ]; then
    # shellcheck disable=1090
    source ~/.cub
    app_id="$WOLFRAM_ALPHA_V2_APP_ID"
else
    echo -n "Enter your Wolfram|Alpha App ID (will be saved to ~/.cub): " && read -r app_id
    echo "WOLFRAM_ALPHA_V2_APP_ID=\"$app_id\"" >> ~/.cub
fi

url="https://api.wolframalpha.com/v2/query?appid=$app_id&input="

echo "$url"
